data:
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  download_path: data/download/data.zip
  data_path: data/extracted
  data_full_path: data/extracted/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail
  transformed_data_path: data/transformed


model:
  model_checkpoint_name: google/pegasus-cnn_dailymail
  model_checkpoint_path: artifacts/models/checkpoints
  trained_model_path: artifacts/models/trained_model


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv
